name: onprem-rag-stack

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_pgvector_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
      TZ: Asia/Jerusalem
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/app/db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - ragnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  ollama:
    build:
      context: ./infra/ollama
      dockerfile: Dockerfile
      args:
        USE_OFFLINE_MODELS: "${USE_OFFLINE_MODELS:-0}"
    container_name: rag_ollama
    restart: unless-stopped
    environment:
      OLLAMA_KEEP_ALIVE: 24h
      TZ: Asia/Jerusalem
    ports:
      - "11434:11434"
    # REMOVE the volumes section to use built-in models
    networks:
      - ragnet
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:11434/api/tags | grep -q 'models' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 120s

networks:
  ragnet:
    driver: bridge

volumes:
  pgdata:
  ollama_models:
