services:
  db:
    image: pgvector/pgvector:pg16              # PostgreSQL 16 with pgvector
    container_name: rag_pgvector_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
      TZ: Asia/Jerusalem
    ports:
      - "5432:5432"
    volumes:
      # Persistent database storage (keeps data between restarts)
      - pgdata:/var/lib/postgresql/data
      # Auto-init SQL scripts (run only on first init of pgdata)
      - ./backend/app/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  # -----------------------------------------------------------
  # 🧭 PostgreSQL GUI (pgAdmin 4)
  # -----------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: rag_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com     # login email
      PGADMIN_DEFAULT_PASSWORD: admin            # login password
      PGADMIN_CONFIG_SERVER_MODE: "False"        # single-user mode
      TZ: Asia/Jerusalem
    ports:
      - "5050:80"                                # open http://localhost:5050
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
